config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users, only: [:index, :new, :show, :create, :edit, :update]
  resources :events, only: [:index, :new, :show, :create, :edit, :update]
  resources :interests, only: [:index, :show]
  get "/login", to: "sessions#new"
  post "/sessions/new", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  patch "/add-guest/:event_id", to: "events#add_guest_to_event", as: "add_guest"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :interest
  has_many :events_guests
  has_many :guests, through: :events_guests, foreign_key: 'guest_id'
  belongs_to :host, class_name: 'User'

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :datetime, presence: true
  validate :event_date_cannot_be_in_the_past

  def event_date_cannot_be_in_the_past
    if datetime.present? && datetime.past?
      errors.add(:date, "of event can't be in the past")
    end
  end

  def add_guest_to_event(guest_obj)
    if !(self.guests.include?(guest_obj))
      self.guests << guest_obj
    end
  end

  def date
    "#{self.datetime.strftime("%B")} #{self.datetime.strftime("%d")}, #{self.datetime.strftime("%Y")}"
  end

  def time
    self.datetime.strftime("%I:%M%p")
  end
end

app/models/events_guest.rb
class EventsGuest < ApplicationRecord
  belongs_to :event
  belongs_to :guest, class_name: 'User'
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :events
  has_many :users, through: :events
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events_guests, foreign_key: 'guest_id'
  has_many :events, through: :events_guests
  has_many :events, foreign_key: 'host_id'
  has_many :interests, through: :events
  has_many :guests, class_name: 'EventsGuest', foreign_key: 'guest_id'

  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :age, presence: true
  validates :password, length: {minimum: 6}
  # validate :user_has_enough_points?

  def has_enough_points?
    self.points >= 100
  end

  def add_points
    total_points = self.points + 100
    self.update_attribute(:points, total_points)
  end

  def subtract_points
    total_points = self.points - 100
    self.update_attribute(:points, total_points)
  end

  def events_user_is_attending
    eventsguests = EventsGuest.all.select {|x| x.guest_id == self.id }
    eventsguests.collect {|x| x.event }
  end

  def already_attending(event_obj)
    if self.events_user_is_attending.include?(event_obj)
      true
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :first_name, :last_name, :no_empty_fields, :events_attending, :logged_in?


  def current_user
    if @current_user
      @current_user
    else
      @current_user = User.find_by(username: cookies[:current_user])
    end
  end

  def first_name(full_name)
    full_name.split(" ")[0]
  end

  def last_name(full_name)
    full_name.split(" ")[-1]
  end

  def no_empty_fields(event_info)
      event_info.select do |info|
        info
      end
  end

  def events_attending(person)
  person.events.find do |x|
     return x.name
     end
  end

  def logged_in?
    current_user != nil
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      @event.host.add_points
      flash[:success] = "Event created! You now have #{@event.host.points} points!"
      redirect_to @event
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event Info Updated!"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def add_guest_to_event
    @event = Event.find(params[:event_id])
    if current_user.has_enough_points?
      if !(current_user.already_attending(@event)) && @event.add_guest_to_event(current_user)
        current_user.subtract_points
        flash[:success] = "You now have #{@event.host.points} points! Can't wait to see you there!"
        redirect_to current_user
      else
        flash[:notice] = "You're already attending this event!"
        redirect_to @event
      end
    else
      flash[:notice] = "Sorry, you don't have enough points to attend. Maybe it's time to host one!"
      redirect_to @event
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :address, :datetime, :points, :host_id, :interest_id)
  end

end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

  def index
    @interests = Interest.all
  end

  def show
    @interest = Interest.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to events_path
    else
      render :new
    end
  end

  def create
    username = params[:username]
    @user = User.find_by(username: username)

    if @user && @user.authenticate(params[:password])
      cookies["current_user"] = username
      redirect_to events_path
    else
      flash.notice = "No user found with that name and password"
      redirect_to login_path
    end
  end

  def destroy
    cookies.delete("current_user")
    redirect_to login_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    cookies.delete("current_user")
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      cookies["current_user"] = @user.username
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :age, :points, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_form.html.erb
<%= bootstrap_form_for @event do |f| %>
  <%= f.text_field :name %>

  <%= f.text_field :address %>

  <%=f.collection_select :interest_id, Interest.all, :id, :name%>

  <div class="field">
    <%= f.datetime_field :datetime %>
  </div>
  
  <% if current_user %>
    <%= f.hidden_field :host_id, value: current_user.id %>
  <% end %>

  <%= f.submit submit_text %>
<% end %>

app/views/events/edit.html.erb
<div class="jumbotron">

<h2>Edit Info for <%= @event.name %></h2>

<%= render partial: "shared/error_list", locals: {new_object: @event} %>
<%= render partial: "event_form", locals: { submit_text: 'Edit Event'} %>
</div>

app/views/events/index.html.erb
<div class="jumbotron">

<h1>All Events</h1>
<%= form_tag interests_path, method: :get do %>
  <%= submit_tag "Sort by Interest Category" %>
<% end %>

<div class="outside">


  <% @events.each do |event|%>
  <ul>
     <li><%= link_to event.name, event%></li>
  </ul>
  <% end %>
</div>
</div>

</div>

app/views/events/new.html.erb
<div class="jumbotron">

<h2>New Event</h2>

<%= render partial: "shared/error_list", locals: {new_object: @event} %>
<%= render partial: "event_form", locals: { submit_text: 'Create Event'} %>

app/views/events/show.html.erb
<div class="jumbotron">

<h2><%= @event.name %></h2>

<ul>
  <% if @event.host == current_user %>
    <li class="list-group-item">Host: You're hosting!</li>
  <% else %>
    <li class="list-group-item">Host: <%= @event.host.name %></li>
  <% end %>

  <li class="list-group-item">Interest: <%= @event.interest.name %></li>

  <li class="list-group-item">Address: <%= @event.address %></li>

  <li class="list-group-item">Date: <%= @event.date %></li>

  <li class="list-group-item">Time: <%= @event.time %></li>

  <% if !(@event.host == current_user) && !(current_user.already_attending(@event)) %>
    <li class="list-group-item">Need 100 points to attend!</li>
  <% end %>

  <% if current_user.already_attending(@event)%>
    <li class="list-group-item">You're attending this event!</li>
  <% end %>
</ul>

<% if @event.host == current_user %>
  <h3>Guests:</h3>
  <% if @event.guests == [] %>
    <h5>None attending yet!</h5>
  <% else %>
    <ul>
      <% @event.guests.each do |guest| %>
        <li>
          <%= guest.name %> | <%= link_to "email" %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<% if !(@event.host == current_user) && !(current_user.already_attending(@event))%>
  <%= form_tag add_guest_path(@event.id), method: :patch do %>
    <%= submit_tag "Attend this Event" %>
  <% end %>
<% end %>

<% if @event.host == current_user %>

    <%= form_tag edit_event_path(@event.id), method: :get do %>
    <%= submit_tag "Edit This Event" %>
    <% end %>

<% end %>

app/views/interests/index.html.erb
<div class="jumbotron">

<h1>Interests</h1>

<ul>
  <% @interests.each do |interest| %>
    <li><%= link_to interest.name, interest %></li>
  <% end %>
</ul>
</div>

app/views/interests/show.html.erb
<div class="jumbotron">

<h2><%= @interest.name %></h2>
<div class="outside-interests">

<ul>
  <% @interest.events.each do |event| %>
    <li><%= link_to event.name, event %></li>
  <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EVENT-ation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <% if current_user %>
    <nav class="nav nav-pills nav-fill fixed-top">
        <div class="nav-item nav-link">

        Welcome <%= first_name(current_user.name)%>
      </div>
        <%= link_to "User Homepage", current_user, :class => 'nav-item nav-link' %>
        <%= link_to "Create New Event", new_event_path, :class => 'nav-item nav-link' %>
        <%= link_to "All Events", events_path, :class => 'nav-item nav-link' %>
        <%= link_to "Logout", '/logout', :class => 'nav-item nav-link'%>
      </nav>
    <% else %>

    <nav class="nav nav-pills nav-fill fixed-top">

        <%= link_to 'Login', '/login', :class => 'nav-item nav-link' %>
         <%= link_to 'Signup', '/signup', :class => 'nav-item nav-link' %>
       </nav>
       <div id="sky">
         <div id="clouds"></div>
       </div>
    <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>

  <%= yield %>

  </body>
</html>

app/views/layouts/new.html.erb
  <div class="jumbotron">
  <h1 class="display-4">EVENT-ation!</h1>
  <p class="lead">Thrive in community by attending events and gaining prime networking connections.</p>
  <hr class="my-4">
  <p>Don't forget to have fun!</p>
  <h1>Login</h1>
  <% if flash.notice%>
  <h3><%= flash.notice %></h3>
  <% end %>
  <%= bootstrap_form_for "/login" do %>
  <%= label :username, "Username" %>
  <%= text_field_tag :username %>
  <br>
  <br>
  <%= label :password, "Password" %>
  <%= password_field_tag :password %>
  <br>
  <br>
  <%= submit_tag "Login", :class => "btn btn-primary btn-lg"%>
  <% end %>
</div>

app/views/shared/_error_list.html.erb
<% if new_object.errors %>
  <ul class="error_list" >
    <% new_object.errors.full_messages.each do |e| %>
      <li class="error">
        <%= e %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/_user_form.html.erb
<%= bootstrap_form_for @user do |f| %>
  <%= f.text_field :username %>
  <%= f.password_field :password%>
  <%= f.text_field :name %>
  <%= f.email_field :email %>
  <%= f.number_field :age %>
  <%= f.submit submit_text, :class => "btn btn-primary btn-lg" %>
<% end %>

app/views/users/edit.html.erb
<div class="jumbotron">

<h2>Edit User</h2>


<%= render partial: "user_form", locals: { submit_text: 'Edit User'} %>
</div>

app/views/users/new.html.erb
<div class="jumbotron">

<h2>Join the Party!</h2>
<%= render partial: "shared/error_list", locals: {new_object: @user} %>

<%= bootstrap_form_for @user do |f| %>
  <%= f.text_field :username %>
  <%= f.password_field :password%>
  <%= f.text_field :name %>
  <%= f.email_field :email %>
  <%= f.number_field :age %>
  <%= f.hidden_field :points, :value => 300 %>
  <%= f.submit "Sign Up", :class => "btn btn-primary btn-lg" %>
<% end %>

</div>

app/views/users/show.html.erb
<div class="jumbotron">

<div class="row">

<div class="col-md-4">

<h2>User Info</h2>

<ul>

<li>First Name: <%= first_name(@user.name) %></li>
<li>Last Name: <%= last_name(@user.name) %></li>
<li>Username: <%= @user.username%> </li>
<li>Email: <%= @user.email%> </li>
<li>Age: <%= @user.age%></li>

<%= form_tag edit_user_path(@user), method: :get do %>
<%= submit_tag "Edit Profile" %>
<% end %>
</div>

<div class="col-md-4">


<h2>Events you are hosting</h2>
<div class="outside-hosting">

<% if @user.events == [] %>
<h4>None! Click <%= link_to "here", new_event_path %> to host one!</h4>
<% end %>

<ul>
<% @user.events.each do |event| %>
  <li><%= link_to event.name, event %></li>
<% end %>
</ul>
</div>
</div>

<div class="col-md-4">

<h2>Events you are attending</h2>
<div class="outside-attending">

<% if @user.events_user_is_attending == [] %>
<h4>None! Click <%= link_to "here", events_path %> to browse!</h4>
<% end %>

<ul>
<% @user.events_user_is_attending.each do |event| %>
  <li><%= link_to event.name, event %></li>
<% end %>
</ul>
</div>
</div>
</div>

</div>